media: assets/images
content: 
  - name: navigation
    label: Navigation
    type: file
    path: _data/navigation.yml
    fields:
      - name: main
        label: Navigation im Header
        type: object
        list: true
        fields:
          - name: title
            label: Titel
            type: string
            required: true
          - name: url
            label: Link (vermutlich einer Datei aus "Seiten")
            type: string
            required: true
            
  - name: home
    label: Home
    type: file
    path: index.md
    icon: house
    fields:
      - name: layout
        label: Layout
        type: select
        options:
          values:
            - value: single 
              label: single (Mittelspalte)
            - value: splash
              label: splash (volle Breite)
        default: single
        required: true
        description: siehe https://mmistakes.github.io/minimal-mistakes/docs/layouts/
      - name: classes
        label: rechte Spalte verwenden
        type: select
        options:
          values: 
            - value: wide
              label: ja (nur bei Layout single sinnvoll)
            - value: 
              label: nein
      - name: title
        label: Titel
        type: string  
        required: true
      - name: header
        label: Header (nur bei Layout splash sinvoll)
        type: object
        fields:
          - name: overlay_color
            label: Overlay Color (färbt das Bild)
            type: string
            description: hex Wert mit hashtag, google "color picker"
          - name: overlay_image
            label: schön großes, breites Bild
            type: image
      - name: excerpt
        label: Text auf Header Bild
        type: text
      - name: sidebar
        label: Bilder in der linken Spalte (nur bei Layout single sinnvoll)
        type: object
        list: true
        fields:
          - name: image
            type: image
      - name: permalink
        label: Link
        type: string
        default: /
        hidden: true
      - name: body
        label: Inhalt
        type: rich-text
        options:
          image:
            path: assets/images
            extensions: [ jpg, jpeg, png ]
            
  - name: pages
    label: Seiten
    type: collection
    path: _pages
    filename: "{fields.title}.md"
    view:
      fields: [ title, permalink ]
    fields:
      - name: title
        label: Titel
        type: string
        required: true
      - name: layout
        label: Layout
        type: select
        options:
          values:
            - value: single 
              label: single (Mittelspalte)
            - value: splash
              label: splash (volle Breite)
        default: single
        required: true
      - name: permalink
        label: Link
        type: string
        required: true
        description: z.B. /imprint/ => erreichbar unter deinedomain.de/imprint/
      - name: classes
        label: rechte Spalte verwenden
        type: select
        default: nein
        options:
          values: 
            - value: wide
              label: ja (nur bei Layout single sinnvoll)
            - value: ""
              label: nein
      - name: header
        label: Header (nur bei Layout splash sinvoll)
        type: object
        fields:
          - name: overlay_color
            label: Overlay Color (färbt das Bild)
            type: string
            description: hex Wert mit hashtag, google "color picker"
          - name: overlay_image
            label: schön großes, breites Bild
            type: image
      - name: excerpt
        label: Text auf Header Bild
        type: text
      - name: sidebar
        label: Bilder in der linken Spalte (nur bei Layout single sinnvoll)
        type: object
        list: true
        fields:
          - name: image
            type: image
      - name: body
        label: inhalt
        type: rich-text

  - name: images
    label: Bilder
    type: file
    path: _specials/images.md
    fields:
      - name: layout
        label: Layout
        type: string
        default: splash
        hidden: true
      - name: permalink
        label: Link
        type: string
      - name: feature_row
        label: Gallerienliste
        type: object
        list: true
        fields:
          - name: image_path
            label: Display Bild
            type: image
            required: true
          - name: alt 
            type: string
            default: ""
            hidden: true
          - name: title
            label: Titel
            type: string
            required: true
          - name: excerpt
            label: Beschreibung
            type: string
          - name: url
            label: Link zu Gallerie
            type: string
            required: true
          - name: btn_class
            type: string
            default: "btn--primary"
            hidden: true
          - name: btn_label
            type: string
            default: "Ansehen"
            hidden: true
      - name: body
        type: string
        default: "{% include feature_row %}"
        hidden: true 
        
  - name: galleries
    label: Gallerien
    type: collection
    path: _galleries
    filename: '{fields.name}.md'
    view:
      fields: [ name, permalink ]
    fields:
      - name: name
        label: Name
        type: string
        description: Name der Datei. Am Besten gleich wie der Name des Bildordners (falls existent, zur Übersicht)
        required: true
      - name: layout
        label: Layout
        type: string
        default: "splash"
        hidden: true
      - name: permalink
        label: Link
        type: string
        required: true
        description: z.B. /imprint/ => erreichbar unter deinedomain.de/imprint/, Eintrag in Bilder nicht vergessen! Am Besten ist /images/<Name>/ 
      - name: gallery
        label: Bilderliste
        type: object
        list: true
        fields:
          - name: image_path
            label: Bild
            type: image
            required: true
      - name: body
        label: Inhalt
        type: rich-text
        default: "{% include gallery %}"
        hidden: true

  - name: styles
    label: Styles
    type: file
    path: _sass/minimal-mistakes/skins/_neon.scss
    fields:
      - name: body
        label: CSS Code
        type: text
 
      
      
        
      
            