media: assets/images
content: 
  - name: imprint
    label: Impressum
    type: file
    path: _pages/imprint.md
    fields:
      - name: title
        label: Titel
        type: string  
      - name: content
        label: Inhalt
        type: rich-text