media: assets/images
content: 
  - name: imprint
    label: Impressum
    type: file
    path: _pages/imprint.md
    icon: map-pinned
    fields:
      - name: layout
        label: Layout
        type: string
        default: splash
      - name: title
        label: Titel
        type: string  
      - name: body
        label: Inhalt
        type: rich-text