media: assets/images
content: 
  - name: imprint
    label: Impressum
    type: file
    path: _pages/imprint.md
    icon: Stamp
    fields:
      - name: layout
        label: Layout
        type: string
        default: splash
      - name: title
        label: Titel
        type: string  
      - name: permalink
        label: Link
        type: string
        description: z.B. /imprint/ => erreichbar unter deinedomain.de/imprint/
      - name: body
        label: Inhalt
        type: rich-text