title: JiMs Bergwerk
description: Betreiber eines Jugendtreff in Bad Aibling, öffentliche Jugendarbeit
url: https://lorenzgartmeier.github.io
repository: LorenzGartmeier/lorenzgartmeier.github.io
logo: /assets/images/logo.png
