title: JiMs Bergwerk
description: Schafft Raum für Jugend in Bad Aibling
url: https://lorenzgartmeier.github.io
repository: LorenzGartmeier/minimal-mistakes
logo: /assets/images/logo.png
copyright: Jugendinitiative Mangfalltal e.V.
search: false
search_full_content: false
encoding: false
