title: "Dominic Minischetti"
description: "PHP Backend Engineer"
url: "https://minischetti.org"
baseurl: ""

author:
  name: "Dominic Minischetti"
  email: "dominic.minischetti@gmail.com"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
