name: "Bug Report"

about: "문제를 설명해 주세요."

title: "버그 보고"
labels:
  - bug
  - help wanted
assignees: []

body:
  - type: "markdown"
    attributes:
      value: |
        ## 문제 설명
        - 버그 또는 문제가 발생한 상황을 상세히 설명해 주세요.
        
        ## 재현 방법
        1. 이 명령을 실행합니다.
        2. 발생한 오류 메시지를 제공합니다.
        
        ## 기대한 결과
        정상적으로 작동해야 합니다.
        
        ## 환경 정보
        - OS: Ubuntu 22.04
        - 버전: 4.1.2


